Portfolio: finish mobile version
naolkidanu/portfolio pull request #2
Opened 2022-09-23 16:49 UTC by naolkidanu

Milestone:
- Add work section
- Add flex to cards
- Add CSS grid to work section

2022-09-23 17:11 UTC, aimalamiri requested changes
Hi @naolkidanu, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191347504-9f70659c-a01f-48a1-ad46-b8722d46ffca.gif)

## Highlights

- The header section is designed very well and look fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

## Required Changes ♻️

- [ ] **Your project looks amazing, but according to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#project--requirements) you must also add the `About myself` section. So make sure to have it in your next commit.**


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-23 17:11 UTC, aimalamiri commented on index.html
> +      <p class="card-name">Tonic</p>
Good job for implementing the same font, but it's highly recommended to use header tags for the titles, so please make sure to put the project name into a `h[1-6]` tag.

2022-09-23 17:11 UTC, aimalamiri commented on index.html
> +      <button class="sec-button">see project</button>
The design of your button looks great, and you can add some effects to improve it. For example, the hover, active, and disabled states, as you can see in the below screenshot from Figma.

![image](https://user-images.githubusercontent.com/34779928/192015264-3039d795-be7c-411f-8cfd-f55f7080f56e.png)

2022-09-23 18:14 UTC, ichala requested changes
Hi @Tushar151997 , 

Good job so far! 👏👏👏 
There are some issues that you still need to work on to go to the next project but you're almost there!

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## To Highlight 🎉

- Good Redme✅ 
- Great Design✅ 
- Linters are passing ✅


 ## Required Changes ♻️

- [ ] **_🛑 as mentioned by the previous reviewer & according to the [project requirements](https://github.com/microverseinc/curriculum-html-css/blob/main/portfolio/2_mobile.md#project--requirements) you must also add the `About myself` section and not only the project  section🛑_** 

## Optional suggestions

- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 09:10 UTC, mwanawabangona approved these changes
Hi @naolkidanu,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:
Congratulations!  
![](https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966)

## Highlights
*   No linter errors :heavy_check_mark:
*   Repo looks professional :briefcase:
*   Solid pull request scroll
*   Good quality commits
*   Good job implementing the requested !! :clap: :clap: :clap:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-24 09:13 UTC, merged

2022-09-24 09:16 UTC, naolkidanu commented
Okay, Thank you for your supportive response.

On Sat, 24 Sept 2022 at 02:10, mwanawabangona ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @naolkidanu <https://github.com/naolkidanu>,
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations!
>
> <https://camo.githubusercontent.com/d348d0cdaa16b202354d12402e048f52cd4d589b4ec0e55f07d62c2f22753376/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f336f373246634a6d4c7a4964594a646d44652f67697068792e676966>
> Highlights
>
>    - No linter errors ✔️
>    - Repo looks professional 💼
>    - Solid pull request scroll
>    - Good quality commits
>    - Good job implementing the requested !! 👏 👏 👏
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/naolkidanu/portfolio/pull/2#pullrequestreview-1119225135>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2LZRNVBAHBRHD2NBTCPHPLV73AQDANCNFSM6AAAAAAQUETW3Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>