Portfolio: desktop version
naolkidanu/portfolio pull request #6
Opened 2022-10-06 17:59 UTC by naolkidanu

##In this PR I have done
-  Add a media query
-  Customize styles to the desktop version
-  Implement responsiveness

2022-10-06 18:51 UTC, aimalamiri requested changes
Hi @naolkidanu, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![AlmostThereReachGIF](https://user-images.githubusercontent.com/34779928/191347504-9f70659c-a01f-48a1-ad46-b8722d46ffca.gif)

## Highlights

- The desktop layout is designed very well and looks fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-06 18:51 UTC, aimalamiri commented on index.html
>      <nav>
Good job! but you need to implement some minor changes, don't worry I'll explain all of them simply.

As you know it's required to follow the exact Figma template, so please make sure to adapt your design to the Figma template.
1. It's required to have a space from left and right in almost all parts of your desktop page.
2. [Optional] Don't you think it'll be a good idea to add a `container` class and use it everywhere to have the same left and right padding for all of your layout contents?
3. Please make sure to use the exact colors as the ones in the Figma design.

![image](https://user-images.githubusercontent.com/34779928/194391495-6ad5dcfd-3e06-47f0-ba15-cdb4feeefefc.png)


![image](https://user-images.githubusercontent.com/34779928/194390974-117ab58a-8bb9-430f-bce0-17728a0bf773.png)

2022-10-06 18:51 UTC, aimalamiri commented on index.html
> +      <div class="Desktop-common">
I can't find where this div is closed. Please try to avoid adding redundant code, and keep your project as clean as possible.

2022-10-06 18:51 UTC, aimalamiri commented on index.html
>          <li class="cann">canopy</li>
It looks great, but to follow the Figma template you can add some padding to the top and left for the content section.

![image](https://user-images.githubusercontent.com/34779928/194393299-7ea09faa-9cd9-4db9-968a-065e6560c8f7.png)

2022-10-06 18:51 UTC, aimalamiri commented on index.html
>          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
Please make sure to follow the exact font size in your language icons as well.

![image](https://user-images.githubusercontent.com/34779928/194394140-af495ff4-9142-42ad-b65f-76886b868564.png)

2022-10-07 09:25 UTC, roshan-bajgain requested changes
Hi @naolkidanu, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-07 09:25 UTC, roshan-bajgain commented on index.html
>          <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 8.25l-7.5 7.5-7.5-7.5" />
- [ ] As requested by the previous reviewer please make sure that the color and font match the design. See image below for reference
### Figma design
![fimga](https://user-images.githubusercontent.com/81727988/194519437-6f406a94-8b1c-4d9b-8a45-5d6f5c68fb55.png)
### Your design
![your](https://user-images.githubusercontent.com/81727988/194519484-bbc9b195-950f-4b60-b27d-51c63880328c.png)

2022-10-07 09:25 UTC, roshan-bajgain commented on index.html
>        experience! If you like what you see and have a project you need coded, don’t hestiate to contact me.</p>
- [ ] [ Optional ] As the requirement you should stick to the design as much as possible that is font, color, and spacing. You don't have spacing before `About section`, If you see the design you will find the spacing so please implement it and also see the image below for reference.
### Your design
![yourrrrrrrrrr](https://user-images.githubusercontent.com/81727988/194520718-94ffbe7b-2520-4175-a85b-e2058fb5e916.png)

 
### Figma design
![figmaaaaaaa](https://user-images.githubusercontent.com/81727988/194520572-32cca7c3-d186-4cd7-bbac-d42ed14dd01e.png)

2022-10-07 10:28 UTC, mckent05 approved these changes
Hi @naolkidanu,

# STATUS: APPROVED ✔️ ✔️  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/194533071-f90ea3b0-a716-4900-8933-20f552479fe7.gif)


## Highlights
- Your repo looks professional 👏 
- All linter check are passing correctly ✔️ ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-07 10:35 UTC, merged

2022-10-07 10:38 UTC, naolkidanu commented
Thank you for your review

On Fri, 7 Oct 2022 at 03:28, Akinlade Temitope ***@***.***>
wrote:

> ***@***.**** approved this pull request.
>
> Hi @naolkidanu <https://github.com/naolkidanu>,
> STATUS: APPROVED ✔️ ✔️
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations and well done! 🎉
> [image: approved]
> <https://user-images.githubusercontent.com/73607512/194533071-f90ea3b0-a716-4900-8933-20f552479fe7.gif>
> Highlights
>
>    - Your repo looks professional 👏
>    - All linter check are passing correctly ✔️ ✔️
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/naolkidanu/portfolio/pull/6#pullrequestreview-1134262889>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A2LZRNWC5BMWCVSFKR35LKDWB73NRANCNFSM6AAAAAAQ63YYNI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>